# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62109feaee9e94177e14c065890c51ecea5a32c666b6ce4900b6be2343b3d838d89cebc388c7b9387254611604919526b7ccdb99975496f0793943cbaf0d01f0

test:
  secret_key_base: dbd7f5884192c1f8eef5e0dcc6b4b36f15fc805c0a4ddeca9217116143aa37228121d5d961fc7de05a702dfdeddc3f3500f4b3791537b195109e3384be810888

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
